---

- hosts: all
  become: true
  tasks:
 
  - name: update respository index
    apt:
      update_cache: yes
  - name: copy files from 
    tags: ubuntu
    copy:
      src: ~/.ssh/ansible_tutorial/files/default_site1.html
      dest: /var/www/html/default_Site1.html
      owner: root
      group: root
      mode: 0644
