---

- hosts: all
  become: true
  tasks:
  
  - name: update respository index
    apt:
      update_cache: yes
  - name: removing apache server
    apt:
      name: apache2
      state: absent
  - name: removing php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
  - name: removing java
    apt:
      name: openjdk-8-jdk
      state: absent 
