---

- hosts: all
  become: true
  tasks:

  - name: install updates on  CentOS
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
  - name: install updates on  ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes   
    when: ansible_distribution == "Ubuntu"

- hosts: db_server
- become: true
  tasks:
  - name: installing apache server
    tags: apache,apache2
    apt:
      name: 
        -  apache2
        -  libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: app_server
- become: true
  tasks:
  - name: install samba
    tags: samba
    apt:
      name: samba
      state: latest   
    when: ansible_distribution == "Ubuntu"

- hosts: file_server
- become: true
  tasks:
    - name:  install maria db ubuntu
      tags: db,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install  maria db centos
      tags: centos,db
      dnf:
        name: maria_db
        state: latest
      when: ansible_distribution == "CentOS"

