- name: installing apache server
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
- name: install java
  apt:
    name: openjdk-8-jdk
    state: present 
- name: upgrade the system
  apt: 
    upgrade: dist      
