- name: creating new user
  user:
    name: ansible
    groups: root
   
- name: add sshkey for ansible user
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEfVHVYnRGp6jJSPdeW+u1HW2SItuwftSJk1DH22C2Qg AnsibleKey"
      
- name: adding sudoers file for anisble user
  copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root   
