- name: checking apache service is available 
  service:
    name: "{{ apache_package_name }}"
    enabled : yes

- name: stopped the service if already started
  service:
    name: "{{ apache_package_name }}"
    state: stopped

- name: start the service 
  service:
    name: "{{ apache_package_name }}"
    state: started
  notify: restart_apache_handlers

- name: reloaded the service
  service:
    name: "{{ apache_package_name }}"
    state: reloaded  

 
