- name: checking apache service is available 
  service:
    name: apache2
    enabled : yes

- name: stopped the service if already started
  service:
    name: apache2
    state: stopped

- name: start the service 
  service:
    name: apache2
    state: started

- name: restart the service
  service:
    name: apache2
    state: restarted

- name: reloaded the service
  service:
    name: apache2
    state: reloaded  

 
